export const dataProperties = [
  {
    id: 1,
    location: "Tuxtla Gutierréz, Chiapas, MX",
    price: 200000,
    bedrooms: 3,
    bathroom: 1,
    image: "propertie1.jpeg",
    star: 4.5,
    meters: 430,
    description:
      "En el corazón de la encantadora ciudad de Tuxtla Gutierréz, te presentamos una oportunidad única de adquirir un espectacular piso de 75 metros cuadrados que combina comodidad, elegancia y un entorno natural inigualable. Esta vivienda, ubicada en una zona tranquila y bien comunicada, es un refugio de paz y belleza que estamos seguros te enamorará.. . Al entrar a este acogedor hogar, te recibirá un amplio recibidor que te conducirá a un baño completo con bañera, perfecto para relajarte después de un largo día. Continuando, te adentrarás en un generoso salón comedor, que se fusiona con la cocina a través de puertas correderas. ",
  },
  {
    id: 2,
    location: "Xalapa, Veracruz, MX",
    price: 150000,
    bedrooms: 2,
    bathroom: 2,
    image: "propertie2.jpeg",
    star: 4,
    meters: 230,
    description:
      "En el corazón de la encantadora ciudad de Xalapa, te presentamos una oportunidad única de adquirir un espectacular piso de 75 metros cuadrados que combina comodidad, elegancia y un entorno natural inigualable. Esta vivienda, ubicada en una zona tranquila y bien comunicada, es un refugio de paz y belleza que estamos seguros te enamorará.. . Al entrar a este acogedor hogar, te recibirá un amplio recibidor que te conducirá a un baño completo con bañera, perfecto para relajarte después de un largo día. Continuando, te adentrarás en un generoso salón comedor, que se fusiona con la cocina a través de puertas correderas. ",
  },
  {
    id: 3,
    location: "Irapuato, Guanajuato, MX",
    price: 450000,
    bedrooms: 5,
    bathroom: 2,
    image: "propertie3.jpeg",
    star: 5,
    meters: 90,
    description:
      "En el corazón de la encantadora ciudad de Irapuato, te presentamos una oportunidad única de adquirir un espectacular piso de 75 metros cuadrados que combina comodidad, elegancia y un entorno natural inigualable. Esta vivienda, ubicada en una zona tranquila y bien comunicada, es un refugio de paz y belleza que estamos seguros te enamorará.. . Al entrar a este acogedor hogar, te recibirá un amplio recibidor que te conducirá a un baño completo con bañera, perfecto para relajarte después de un largo día. Continuando, te adentrarás en un generoso salón comedor, que se fusiona con la cocina a través de puertas correderas. ",
  },
  {
    id: 4,
    location: "Tehuacán, Puebla, MX",
    price: 700000,
    bedrooms: 3,
    bathroom: 1,
    image: "propertie4.jpeg",
    star: 4.2,
    meters: 120,
    description:
      "En el corazón de la encantadora ciudad de Tehuacán, te presentamos una oportunidad única de adquirir un espectacular piso de 75 metros cuadrados que combina comodidad, elegancia y un entorno natural inigualable. Esta vivienda, ubicada en una zona tranquila y bien comunicada, es un refugio de paz y belleza que estamos seguros te enamorará.. . Al entrar a este acogedor hogar, te recibirá un amplio recibidor que te conducirá a un baño completo con bañera, perfecto para relajarte después de un largo día. Continuando, te adentrarás en un generoso salón comedor, que se fusiona con la cocina a través de puertas correderas. ",
  },
  {
    id: 5,
    location: "Cuernavaca, Morelos, MX",
    price: 300000,
    bedrooms: 3,
    bathroom: 1,
    image: "propertie5.jpeg",
    star: 4.1,
    meters: 87,
    description:
      "En el corazón de la encantadora ciudad de Cuernavaca, te presentamos una oportunidad única de adquirir un espectacular piso de 75 metros cuadrados que combina comodidad, elegancia y un entorno natural inigualable. Esta vivienda, ubicada en una zona tranquila y bien comunicada, es un refugio de paz y belleza que estamos seguros te enamorará.. . Al entrar a este acogedor hogar, te recibirá un amplio recibidor que te conducirá a un baño completo con bañera, perfecto para relajarte después de un largo día. Continuando, te adentrarás en un generoso salón comedor, que se fusiona con la cocina a través de puertas correderas. ",
  },
  {
    id: 6,
    location: "Monterrey, Nuevo León, MX",
    price: 500000,
    bedrooms: 3,
    bathroom: 1,
    image: "propertie6.jpeg",
    star: 3.7,
    meters: 220,
    description:
      "En el corazón de la encantadora ciudad de Monterrey, te presentamos una oportunidad única de adquirir un espectacular piso de 75 metros cuadrados que combina comodidad, elegancia y un entorno natural inigualable. Esta vivienda, ubicada en una zona tranquila y bien comunicada, es un refugio de paz y belleza que estamos seguros te enamorará.. . Al entrar a este acogedor hogar, te recibirá un amplio recibidor que te conducirá a un baño completo con bañera, perfecto para relajarte después de un largo día. Continuando, te adentrarás en un generoso salón comedor, que se fusiona con la cocina a través de puertas correderas. ",
  },
  {
    id: 7,
    location: "Ciudad Victoria, Tamaulipas, MX",
    price: 800000,
    bedrooms: 3,
    bathroom: 1,
    image: "propertie7.jpeg",
    star: 4.5,
    meters: 430,
    description:
      "En el corazón de la encantadora ciudad Victoria, te presentamos una oportunidad única de adquirir un espectacular piso de 75 metros cuadrados que combina comodidad, elegancia y un entorno natural inigualable. Esta vivienda, ubicada en una zona tranquila y bien comunicada, es un refugio de paz y belleza que estamos seguros te enamorará.. . Al entrar a este acogedor hogar, te recibirá un amplio recibidor que te conducirá a un baño completo con bañera, perfecto para relajarte después de un largo día. Continuando, te adentrarás en un generoso salón comedor, que se fusiona con la cocina a través de puertas correderas. ",
  },
  {
    id: 8,
    location: "Chihuahua, Chihuahua, MX",
    price: 1200000,
    bedrooms: 3,
    bathroom: 1,
    image: "propertie8.jpeg",
    star: 4.5,
    meters: 330,
    description:
      "En el corazón de la encantadora ciudad de Chihuahua, te presentamos una oportunidad única de adquirir un espectacular piso de 75 metros cuadrados que combina comodidad, elegancia y un entorno natural inigualable. Esta vivienda, ubicada en una zona tranquila y bien comunicada, es un refugio de paz y belleza que estamos seguros te enamorará.. . Al entrar a este acogedor hogar, te recibirá un amplio recibidor que te conducirá a un baño completo con bañera, perfecto para relajarte después de un largo día. Continuando, te adentrarás en un generoso salón comedor, que se fusiona con la cocina a través de puertas correderas. ",
  },
  {
    id: 9,
    location: "Torreón, Coahuila, MX",
    price: 400000,
    bedrooms: 3,
    bathroom: 1,
    image: "propertie9.jpeg",
    star: 4.5,
    meters: 380,
    description:
      "En el corazón de la encantadora ciudad de Torreón, te presentamos una oportunidad única de adquirir un espectacular piso de 75 metros cuadrados que combina comodidad, elegancia y un entorno natural inigualable. Esta vivienda, ubicada en una zona tranquila y bien comunicada, es un refugio de paz y belleza que estamos seguros te enamorará.. . Al entrar a este acogedor hogar, te recibirá un amplio recibidor que te conducirá a un baño completo con bañera, perfecto para relajarte después de un largo día. Continuando, te adentrarás en un generoso salón comedor, que se fusiona con la cocina a través de puertas correderas. ",
  },
  {
    id: 10,
    location: "Tijuana, Tijuana, MX",
    price: 750000,
    bedrooms: 3,
    bathroom: 1,
    image: "propertie10.jpeg",
    star: 4.1,
    meters: 270,
    description:
      "En el corazón de la encantadora ciudad de Tijuana, te presentamos una oportunidad única de adquirir un espectacular piso de 75 metros cuadrados que combina comodidad, elegancia y un entorno natural inigualable. Esta vivienda, ubicada en una zona tranquila y bien comunicada, es un refugio de paz y belleza que estamos seguros te enamorará.. . Al entrar a este acogedor hogar, te recibirá un amplio recibidor que te conducirá a un baño completo con bañera, perfecto para relajarte después de un largo día. Continuando, te adentrarás en un generoso salón comedor, que se fusiona con la cocina a través de puertas correderas. ",
  },
  {
    id: 11,
    location: "Tepic, Nayarit, MX",
    price: 1100000,
    bedrooms: 3,
    bathroom: 1,
    image: "propertie11.jpeg",
    star: 5,
    meters: 430,
    description:
      "En el corazón de la encantadora ciudad de Tepic, te presentamos una oportunidad única de adquirir un espectacular piso de 75 metros cuadrados que combina comodidad, elegancia y un entorno natural inigualable. Esta vivienda, ubicada en una zona tranquila y bien comunicada, es un refugio de paz y belleza que estamos seguros te enamorará.. . Al entrar a este acogedor hogar, te recibirá un amplio recibidor que te conducirá a un baño completo con bañera, perfecto para relajarte después de un largo día. Continuando, te adentrarás en un generoso salón comedor, que se fusiona con la cocina a través de puertas correderas. ",
  },
  {
    id: 12,
    location: "Guadalajara, Jalisco, MX",
    price: 500000,
    bedrooms: 3,
    bathroom: 1,
    image: "propertie12.jpeg",
    star: 3.9,
    meters: 76,
    description:
      "En el corazón de la encantadora ciudad de Guadalajara, te presentamos una oportunidad única de adquirir un espectacular piso de 75 metros cuadrados que combina comodidad, elegancia y un entorno natural inigualable. Esta vivienda, ubicada en una zona tranquila y bien comunicada, es un refugio de paz y belleza que estamos seguros te enamorará.. . Al entrar a este acogedor hogar, te recibirá un amplio recibidor que te conducirá a un baño completo con bañera, perfecto para relajarte después de un largo día. Continuando, te adentrarás en un generoso salón comedor, que se fusiona con la cocina a través de puertas correderas. ",
  },
  {
    id: 13,
    location: "Mérida, Yucatán, MX",
    price: 800000,
    bedrooms: 3,
    bathroom: 1,
    image: "propertie13.jpeg",
    star: 4.8,
    meters: 290,
    description:
      "En el corazón de la encantadora ciudad de Mérida, te presentamos una oportunidad única de adquirir un espectacular piso de 75 metros cuadrados que combina comodidad, elegancia y un entorno natural inigualable. Esta vivienda, ubicada en una zona tranquila y bien comunicada, es un refugio de paz y belleza que estamos seguros te enamorará.. . Al entrar a este acogedor hogar, te recibirá un amplio recibidor que te conducirá a un baño completo con bañera, perfecto para relajarte después de un largo día. Continuando, te adentrarás en un generoso salón comedor, que se fusiona con la cocina a través de puertas correderas. ",
  },
  {
    id: 14,
    location: "Guadalajara, Jalisco, MX",
    price: 250000,
    bedrooms: 3,
    bathroom: 1,
    image: "propertie14.jpeg",
    star: 4.9,
    meters: 180,
    description:
      "En el corazón de la encantadora ciudad de Guadalajara, te presentamos una oportunidad única de adquirir un espectacular piso de 75 metros cuadrados que combina comodidad, elegancia y un entorno natural inigualable. Esta vivienda, ubicada en una zona tranquila y bien comunicada, es un refugio de paz y belleza que estamos seguros te enamorará.. . Al entrar a este acogedor hogar, te recibirá un amplio recibidor que te conducirá a un baño completo con bañera, perfecto para relajarte después de un largo día. Continuando, te adentrarás en un generoso salón comedor, que se fusiona con la cocina a través de puertas correderas. ",
  },
  {
    id: 15,
    location: "León, Guanajuato, MX",
    price: 1100000,
    bedrooms: 3,
    bathroom: 1,
    image: "propertie15.jpeg",
    star: 4.1,
    meters: 287,
    description:
      "En el corazón de la encantadora ciudad de León, te presentamos una oportunidad única de adquirir un espectacular piso de 75 metros cuadrados que combina comodidad, elegancia y un entorno natural inigualable. Esta vivienda, ubicada en una zona tranquila y bien comunicada, es un refugio de paz y belleza que estamos seguros te enamorará.. . Al entrar a este acogedor hogar, te recibirá un amplio recibidor que te conducirá a un baño completo con bañera, perfecto para relajarte después de un largo día. Continuando, te adentrarás en un generoso salón comedor, que se fusiona con la cocina a través de puertas correderas. ",
  },
  {
    id: 16,
    location: "Monterrey, Nuevo Léon, MX",
    price: 1200000,
    bedrooms: 3,
    bathroom: 1,
    image: "propertie16.jpeg",
    star: 4,
    meters: 290,
    description:
      "En el corazón de la encantadora ciudad de Monterrey, te presentamos una oportunidad única de adquirir un espectacular piso de 75 metros cuadrados que combina comodidad, elegancia y un entorno natural inigualable. Esta vivienda, ubicada en una zona tranquila y bien comunicada, es un refugio de paz y belleza que estamos seguros te enamorará.. . Al entrar a este acogedor hogar, te recibirá un amplio recibidor que te conducirá a un baño completo con bañera, perfecto para relajarte después de un largo día. Continuando, te adentrarás en un generoso salón comedor, que se fusiona con la cocina a través de puertas correderas. ",
  },
];
